"""Generate the dashboard's JS translation dict from tools/i18n_strings.py.

One source of truth: the Python table feeds the annotator, the Persian linter,
AND this generator. Writing the dict by hand in the HTML would let the three
drift apart, and a drifted key renders as a raw placeholder in the UI.

Idempotent — rewrites everything between the two marker comments.
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from i18n_strings import ATTRS, JS_STRINGS, STRINGS  # noqa: E402

DASH = os.path.join(os.path.dirname(__file__), "..", "dashboard.html")
START = "/* ══ I18N-DICT-START (generated by tools/i18n_gen.py — do not edit) ══ */"
END = "/* ══ I18N-DICT-END ══ */"


def main() -> int:
    en: dict[str, str] = {}
    fa: dict[str, str] = {}
    for table in (STRINGS, ATTRS, JS_STRINGS):
        for key, e, f in table:
            if key in en:
                print(f"DUPLICATE KEY {key}")
                return 1
            # The tables carry HTML entities because they mirror the markup;
            # decode them here so JS can assign to .textContent safely (which
            # escapes on its own — assigning '&amp;' would render literally).
            en[key] = e.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
            fa[key] = f.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")

    block = (
        f"{START}\n"
        f"const I18N = {{\n"
        f"  en: {json.dumps(en, ensure_ascii=False, indent=2, sort_keys=True)},\n"
        f"  fa: {json.dumps(fa, ensure_ascii=False, indent=2, sort_keys=True)}\n"
        f"}};\n"
        f"{END}"
    )

    html = open(DASH, encoding="utf-8").read()
    if START in html:
        s = html.index(START)
        e = html.index(END) + len(END)
        html = html[:s] + block + html[e:]
    else:
        print("marker not found — add the I18N-DICT markers to dashboard.html first")
        return 1
    open(DASH, "w", encoding="utf-8").write(html)
    print(f"wrote dict: {len(en)} keys x 2 languages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
